---
# Global CI/CD permission boundary and Serverless deployment bucket per AWS account.
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # PermissionBoundary has an explicit deny all. The boundary sets the maximum set of permissions.
  ServerlessPermissionBoundary:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: serverless-permission-boundary
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowIAMReadOnly
            Effect: Allow
            Action:
              - iam:Get*
              - iam:List*
              - iam:SimulatePrincipalPolicy
            Resource:
              - "*"
          - Sid: AllowServerlessServices
            Effect: Allow
            Action:
              - apigateway:*
              - cloudwatch:*
              - cognito-idp:*
              - dynamodb:*
              - ec2:CreateNetworkInterface
              - ec2:DeleteNetworkInterface
              - ec2:Describe*
              - events:*
              - kms:*
              - lambda:*
              - logs:*
              - s3:*
              - schemas:*
              - sns:*
              - sqs:*
              - ssm:*
              - states:*
              - synthetics:*
              - xray:*
            Resource:
              - "*"
            Condition:
              StringEquals:
                aws:RequestedRegion:
                  - us-east-1 # Allow North Virginia for CloudFront.
                  - eu-west-1 # Europe.
          - Sid: DenyDynamoRowLevelActions
            Effect: Deny
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:DeleteItem
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:Query
              - dynamodb:PutItem
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Resource:
              - "*"
          - Sid: AllowCloudFormationDeployment
            Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:DescribeStackEvents
              - cloudformation:DescribeStackResources
              - cloudformation:DescribeStacks
              - cloudformation:GetTemplate
              - cloudformation:ListStackResources
              - cloudformation:UpdateStack
              - cloudformation:ValidateTemplate
              - cloudformation:DeleteStack
            Resource:
              - "*"
            Condition:
              StringEquals:
                aws:RequestedRegion:
                  - us-east-1 # Allow North Virginia for CloudFront.
                  - eu-west-1 # Europe.
          - Sid: AllowPassRoleToLambda
            Effect: Allow
            Action:
              - iam:PassRole
            Resource:
              - arn:aws:iam:::role/*
            Condition:
              StringEquals:
                iam:PassedToService: lambda.amazonaws.com
          - Sid: ExplicitDenyPermBoundaryIAMPolicyAlteration
            Effect: Deny
            Action:
              - iam:CreatePolicyVersion
              - iam:DeletePolicy
              - iam:DeletePolicyVersion
              - iam:SetDefaultPolicyVersion
            Resource:
              - arn:aws:iam:::policy/serverless-permission-boundary
          - Sid: ExplicitDenyRemovalOfPermBoundaryFromAnyRole
            Effect: Deny
            Action:
              - iam:DeleteRolePermissionsBoundary
            Resource:
              - arn:aws:iam:::role/*
            Condition:
              StringEquals:
                iam:PermissionsBoundary: arn:aws:iam:::policy/serverless-permission-boundary
          - Sid: AllowUpsertRoleIfPermBoundaryIsBeingApplied
            Effect: Allow
            Action:
              - iam:CreateRole
              - iam:PutRolePolicy
              - iam:PutRolePermissionsBoundary
            Resource:
              - "*"
            Condition:
              StringEquals:
                # The permission boundary needs to explitly provide the account.
                iam:PermissionsBoundary: !Sub "arn:aws:iam:${AWS::AccountId}:policy/serverless-permission-boundary"
          - Sid: AllowDeleteRole
            Effect: Allow
            Action:
              - iam:DeleteRolePolicy
              - iam:DeleteRole
            Resource:
              - "*"

  # Instead of using Serverless Framework to create a bucket, create your own so that we can control the policy more carefully.
  # This also reduces the number of buckets that are lying around.
  # The serverless.yaml can be configured to use this by adding a provider/deploymentBucket section.
  ServerlessDeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration: # Optional, can be used to reduce wasted storage if you don't need old versions to be retained.
        Rules:
          - AbortIncompleteMultipartUpload: # Abandon incomplete uploads after 7 days.
              DaysAfterInitiation: 7
            Status: Enabled
          - NoncurrentVersionExpirationInDays: 7 # Delete old versions of files after 7 days. Think about whether this meets your audit requirements.
            Status: Enabled
      PublicAccessBlockConfiguration: # Disallow public buckets.
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration: # Enable versioning.
        Status: Enabled
  ServerlessDeploymentBucketPolicy: # Policy to disable non HTTPS access, and enforce MFA delete.
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ServerlessDeploymentBucket
      PolicyDocument:
        Statement:
          - Sid: RequireTLS
            Effect: Deny
            Principal: "*"
            Action: "*"
            Resource:
              !Join ["", ["arn:aws:s3:::", !Ref ServerlessDeploymentBucket]]
            Condition:
              Bool:
                "aws:SecureTransport": false
          - Sid: RequireMFAForBucketDeletion
            Effect: Deny
            Principal: "*"
            Action:
              - s3:DeleteBucket
            Resource:
              !Join ["", ["arn:aws:s3:::", !Ref ServerlessDeploymentBucket]]
            Condition:
              "Null":
                "aws:MultiFactorAuthAge": true

Outputs:
  ServerlessPermissionBoundary:
    Description: The global CI permission boundary.
    Value: !Ref ServerlessPermissionBoundary
    Export:
        Name: ServerlessPermissionBoundary
  ServerlessDeploymentBucket:
    Description: The global CI permission boundary.
    Value: !Ref ServerlessDeploymentBucket
    Export:
        Name: ServerlessDeploymentBucket
